l_english:
 give_up_hegemony_title:0 "Surrender Our Hegemony"
 give_up_hegemony_desc:0 "Every Empire must fall sooner or later. Our time has finally come."
 give_up_hegemony_desc:0 "Every Empire must fall sooner or later. Our time has finally come."
 expanded_infra_potential_title:0 "Expand Infrastructure Potential"
 expanded_infra_potential_desc:0 "I love trains."
 advisor_events_check_title:0 "Advisor Events Check"
 advisor_events_check_desc:0 "Get out until I'm fighting a REAL war."
